---
title: "Untitled"
author: "Kevin Cummiskey"
date: "January 17, 2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, warning = FALSE, message= FALSE}
library(tidyverse)
library(Lahman)
```


```{r, fig.height=2}
#Number of wins in a season (2018)
Teams %>%
  filter(yearID == 2018) %>%
  ggplot(aes(x = lgID, y = W)) +
  geom_boxplot() +
  labs(x = "league", y = "Wins", 
       title = "Number of wins by team (2018)")

#Number of wins vs homeruns
Teams %>%
  filter(yearID == 2018) %>%
  ggplot(aes(x = HR, 
             y = W,
             color = lgID)) +
  geom_point() +
  labs(x = "Homeruns", y = "Wins",
       title = "Home Run vs Wins (2018)") +
  geom_smooth(method = "lm")
```


```{r}
complete.games = Teams %>%
  filter(yearID > 1969) %>%
  group_by(yearID, lgID) %>%
  summarize(CG.frac = sum(CG)/sum(G))

complete.games %>%
  ggplot(aes(x = yearID, y = CG.frac, color = lgID)) +
  geom_point() +
  labs(x = "years", y = "complete games(fraction)",
       title = "Fraction of complete games (1970-2018)")
```



